import { Entity, Column, ManyToOne, JoinColumn } from 'typeorm';
import { BaseEntity } from '../../common/entities/base.entity';
import { Recommendation } from './recommendation.entity';
import { Routine } from '../../routines/entities/routine.entity';

export enum RecommendationItemType {
  EXISTING = 'existing', // From user's existing routines
  AI_GENERATED = 'ai_generated', // Newly generated by AI
}

@Entity('recommendation_items')
export class RecommendationItem extends BaseEntity {
  @Column()
  recommendationId: string;

  @ManyToOne(() => Recommendation, (recommendation) => recommendation.items)
  @JoinColumn({ name: 'recommendationId' })
  recommendation: Recommendation;

  @Column({ nullable: true })
  routineId?: string;

  @ManyToOne(() => Routine, { nullable: true })
  @JoinColumn({ name: 'routineId' })
  routine?: Routine;

  @Column({
    type: 'varchar',
    length: 20,
  })
  itemType: RecommendationItemType;

  @Column('text', { nullable: true })
  reasoning?: string;

  @Column({ default: 0 })
  priority: number; // Higher number = higher priority

  @Column('jsonb', { nullable: true })
  routineData?: {
    // For AI-generated routines that aren't saved yet
    name: string;
    description: string;
    estimatedDuration?: number;
    exercises: Array<{
      name: string;
      sets?: number;
      reps?: number;
      notes?: string;
    }>;
    videoUrl?: string;
  };
}
